
development:
  adapter: postgresql
  encoding: unicode
  database: invSy_development
  pool: 5
  username: postgres
  password: admin
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: invSy_test
  pool: 5
  username: postgres
  password: admin
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: invSy_production
  pool: 5
  username: postgres
  password: admin
  host: localhost
